apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-crossplane-postgres
rules:
- apiGroups:
  - postgresql.k8s.enterprisedb.io/v1
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch