{{- range $.Values.configuration.packages }}
{{ if ne . "" }}
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: {{ regexReplaceAll "(:|@).*" (regexReplaceAll ".*/" . "") "" | trim  }}
spec:
  packagePullPolicy: Always
  package: {{ . | trim }}
{{- with $.Values.configuration.packagePullSecrets }}
  packagePullSecrets:
  {{- range $.Values.configuration.packagePullSecrets }}
  - name: {{ .| trim  }}
  {{- end }}
{{- end }}
---
{{ end }}
{{- end }}
