apiVersion: v1
data:
  bedrock_shim: data
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ibm-crossplane-operator
    app.kubernetes.io/managed-by: ibm-crossplane-operator
    app.kubernetes.io/name: ibm-crossplane
  name: crossplane-config
