apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-crossplane-operator
    app.kubernetes.io/managed-by: ibm-crossplane-operator
    app.kubernetes.io/name: ibm-crossplane
  name: ibm-crossplane-provider-ibm-cloud
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - delete
  - list
  - create
  - update
  - patch
  - watch
