---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-crossplane
rules:
# for crossplane to list CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- verbs:
  - get
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - kafkacomposites.shim.bedrock.ibm.com
  - kafkaclaims.shim.bedrock.ibm.com
# for crossplane to register crossplane events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
# for crossplane to manage connection secrets
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - watch
# for crossplane to manage crossplane resources
- apiGroups:
  - apiextensions.crossplane.io
  - pkg.crossplane.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# for crossplane to manage bedrock shim resources
- apiGroups:
  - shim.bedrock.ibm.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch