---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-crossplane
rules:
# for operator to create clusterroles
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  resourceNames:
  - ibm-crossplane
  - ibm-crossplane-bedrock-shim
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
# for operator to create clusterrolebindings
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  resourceNames:
  - ibm-crossplane
  - ibm-crossplane-bedrock-shim
  verbs:
  - delete
  - get
  - patch
# for crossplane to manage provider CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# for crossplane to register crossplane events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
# for crossplane to manage connection secrets
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - watch
# for crossplane to manage crossplane resources
- apiGroups:
  - apiextensions.crossplane.io
  - pkg.crossplane.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# for crossplane to manage bedrock shim resources
- apiGroups:
  - shim.bedrock.ibm.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch