apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-crossplane-kafka
rules:
- verbs:
  - get
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - kafkacomposites.shim.bedrock.ibm.com
  - kafkaclaims.shim.bedrock.ibm.com
- apiGroups:
  - shim.bedrock.ibm.com
  resources:
  - kafkaclaims
  - kafkacomposites
  - kafkaclaims/finalizers
  - kafkacomposites/finalizers
  - kafkaclaims/status
  - kafkacomposites/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch