apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-crossplane-kafka
rules:
- apiGroups:
  - ibmevents.ibm.com
  resources:
  - kafkas
  - kafkausers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch