kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-crossplane-provider-kubernetes
rules:
  - verbs:
      - list
      - watch
      - update
    apiGroups:
      - kubernetes.crossplane.io
    resources:
      - objects
      - objects/status
      - providerconfigs
      - providerconfigs/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - kubernetes.crossplane.io
    resources:
      - providerconfigusages
# to be deleted. Problematic function:
# PublishConnection()
# in:
# .work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/reconciler/managed/reconciler.go
# TODO !!!!!!!!
  - verbs:
      - get
      - delete
      - list
      - create
      - patch
      - watch
    apiGroups:
      - ''
    resources:
      - secrets