apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-crossplane-provider-ibm-cloud
  labels:
    app.kubernetes.io/instance: ibm-crossplane-operator
    app.kubernetes.io/managed-by: ibm-crossplane-operator
    app.kubernetes.io/name: ibm-crossplane
rules:
  - verbs:
      - get
    apiGroups:
      - operator.ibm.com
    resources:
      - namespacescopes
  - verbs:
      - get
      - delete
      - list
      - create
      - update
      - patch
      - watch
    apiGroups:
      - ''
    resources:
      - secrets 