---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-crossplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-crossplane
subjects:
- kind: ServiceAccount
  name: ibm-crossplane
  namespace: ibm-crossplane-system