apiVersion: pkg.ibm.crossplane.io/v1
kind: Configuration
metadata:
  labels:
    app.kubernetes.io/instance: ibm-crossplane-operator
    app.kubernetes.io/managed-by: ibm-crossplane-operator
    app.kubernetes.io/name: ibm-crossplane
  name: ibm-crossplane-bedrock-shim-config
spec:
  ignoreCrossplaneConstraints: false
  package: 'quay.io/opencloudio/ibm-crossplane-bedrock-shim-config:1.3.0'
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false