---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-crossplane-kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-crossplane-kafka
subjects:
- kind: ServiceAccount
  name: ibm-crossplane
  namespace: ibm-common-services