kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: kafkaclaims.shim.bedrock.ibm.com
spec:
  group: shim.bedrock.ibm.com
  names:
    plural: kafkaclaims
    singular: kafkaclaim
    kind: KafkaClaim
    listKind: KafkaClaimList
    categories:
      - claim
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              required:
                - parameters
              properties:
                compositionRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                compositionSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                parameters:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                resourceRef:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                writeConnectionSecretToRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
            status:
              type: object
              properties:
                conditions:
                  description: Conditions of the resource.
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                connectionDetails:
                  type: object
                  properties:
                    lastPublishedTime:
                      type: string
                      format: date-time
                resourceRef:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: READY
          type: string
          jsonPath: '.status.conditions[?(@.type==''Ready'')].status'
        - name: CONNECTION-SECRET
          type: string
          jsonPath: .spec.writeConnectionSecretToRef.name
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
