# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
- bases/apiextensions.ibm.crossplane.io_compositions.yaml
- bases/pkg.ibm.crossplane.io_configurationrevisions.yaml
- bases/pkg.ibm.crossplane.io_configurations.yaml
- bases/pkg.ibm.crossplane.io_controllerconfigs.yaml
- bases/pkg.ibm.crossplane.io_locks.yaml
- bases/pkg.ibm.crossplane.io_providerrevisions.yaml
- bases/pkg.ibm.crossplane.io_providers.yaml
- bases/apiextensions.crossplane.io_kafkaclaims.yaml
- bases/apiextensions.crossplane.io_kafkacomposites.yaml
# +kubebuilder:scaffold:crdkustomizeresource
