# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- ./bases/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
- ./bases/apiextensions.ibm.crossplane.io_compositions.yaml
- ./bases/pkg.ibm.crossplane.io_configurationrevisions.yaml
- ./bases/pkg.ibm.crossplane.io_configurations.yaml
- ./bases/pkg.ibm.crossplane.io_controllerconfigs.yaml
- ./bases/pkg.ibm.crossplane.io_locks.yaml
- ./bases/pkg.ibm.crossplane.io_providerrevisions.yaml
- ./bases/pkg.ibm.crossplane.io_providers.yaml
- ./bases/shim.bedrock.ibm.com_kafkaclaims.yaml
- ./bases/shim.bedrock.ibm.com_kafkacomposites.yaml
- ./bases/shim.bedrock.ibm.com_postgresclaims.yaml
- ./bases/shim.bedrock.ibm.com_postgrescomposites.yaml
- ./bases/apiextensions.ibm.crossplane.io_compositionrevisions.yaml
# +kubebuilder:scaffold:crdkustomizeresource

commonLabels:
  app.kubernetes.io/instance: ibm-crossplane-operator
  app.kubernetes.io/managed-by: ibm-crossplane-operator
  app.kubernetes.io/name: ibm-crossplane
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
