kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: kafkacomposites.shim.bedrock.ibm.com
spec:
  group: shim.bedrock.ibm.com
  names:
    plural: kafkacomposites
    singular: kafkacomposite
    kind: KafkaComposite
    listKind: KafkaCompositeList
    categories:
      - composite
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - parameters
              properties:
                claimRef:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - namespace
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                compositionRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                compositionSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                parameters:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                resourceRefs:
                  type: array
                  items:
                    type: object
                    required:
                      - apiVersion
                      - kind
                      - name
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                user:
                  type: object
                  properties:
                    topicPrefix:
                      description: Topic Prefix
                      type: string
                writeConnectionSecretToRef:
                  type: object
                  required:
                    - name
                    - namespace
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
            status:
              type: object
              properties:
                conditions:
                  description: Conditions of the resource.
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                connectionDetails:
                  type: object
                  properties:
                    lastPublishedTime:
                      type: string
                      format: date-time
                resourceRef:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: READY
          type: string
          jsonPath: '.status.conditions[?(@.type==''Ready'')].status'
        - name: COMPOSITION
          type: string
          jsonPath: .spec.compositionRef.name
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None