kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: kafkaclaims.shim.bedrock.ibm.com
spec:
  group: shim.bedrock.ibm.com
  names:
    plural: kafkaclaims
    singular: kafkaclaim
    kind: KafkaClaim
    listKind: KafkaClaimList
    categories:
      - claim
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - parameters
              properties:
                compositionRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                compositionSelector:
                  type: object
                  required:
                    - matchLabels
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                parameters:
                  type: object
                  properties:
                    kafka:
                      type: object
                      properties:
                        replicas:
                          description: Replicas
                          type: integer
                        resources:
                          description: >-
                            ResourceRequirements describes the compute resource
                            requirements.
                          type: object
                          properties:
                            limits:
                              description: >-
                                Limits describes the maximum amount of compute
                                resources allowed. More info:
                                https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
                              type: object
                              additionalProperties:
                                pattern: >-
                                  ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                anyOf:
                                  - type: integer
                                  - type: string
                                x-kubernetes-int-or-string: true
                            requests:
                              description: >-
                                Requests describes the minimum amount of compute
                                resources required. If Requests is omitted for a
                                container, it defaults to Limits if that is
                                explicitly specified, otherwise to an
                                implementation-defined value. More info:
                                https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
                              type: object
                              additionalProperties:
                                pattern: >-
                                  ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                anyOf:
                                  - type: integer
                                  - type: string
                                x-kubernetes-int-or-string: true
                        storage:
                          type: object
                          properties:
                            class:
                              type: string
                            size:
                              type: string
                            type:
                              type: string
                              enum:
                                - persistent
                                - persistent-claim
                                - transient
                                - ephemeral
                    throughput:
                      description: Throughput
                      type: integer
                    zookeeper:
                      type: object
                      properties:
                        replicas:
                          description: Replicas
                          type: integer
                        resources:
                          description: >-
                            ResourceRequirements describes the compute resource
                            requirements.
                          type: object
                          properties:
                            limits:
                              description: >-
                                Limits describes the maximum amount of compute
                                resources allowed. More info:
                                https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
                              type: object
                              additionalProperties:
                                pattern: >-
                                  ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                anyOf:
                                  - type: integer
                                  - type: string
                                x-kubernetes-int-or-string: true
                            requests:
                              description: >-
                                Requests describes the minimum amount of compute
                                resources required. If Requests is omitted for a
                                container, it defaults to Limits if that is
                                explicitly specified, otherwise to an
                                implementation-defined value. More info:
                                https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
                              type: object
                              additionalProperties:
                                pattern: >-
                                  ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                anyOf:
                                  - type: integer
                                  - type: string
                                x-kubernetes-int-or-string: true
                        storage:
                          type: object
                          properties:
                            class:
                              type: string
                            size:
                              type: string
                            type:
                              type: string
                              enum:
                                - persistent
                                - persistent-claim
                                - transient
                                - ephemeral
                resourceRef:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                user:
                  type: object
                  properties:
                    topicPrefix:
                      description: Topic Prefix
                      type: string
                writeConnectionSecretToRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
            status:
              type: object
              properties:
                conditions:
                  description: Conditions of the resource.
                  type: array
                  items:
                    type: object
                    required:
                      - lastTransitionTime
                      - reason
                      - status
                      - type
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                connectionDetails:
                  type: object
                  properties:
                    lastPublishedTime:
                      type: string
                      format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: READY
          type: string
          jsonPath: '.status.conditions[?(@.type==''Ready'')].status'
        - name: CONNECTION-SECRET
          type: string
          jsonPath: .spec.writeConnectionSecretToRef.name
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
  conversion:
    strategy: None
