---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crossplanes.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: Crossplane
    listKind: CrossplaneList
    plural: crossplanes
    singular: crossplane
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Crossplane is the Schema for the crossplanes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Crossplane
            properties:
              configuration:
                properties:
                  packages:
                    description: Configuration packages to be installed
                    items:
                      type: string
                    type: array
                  packagePullSecrets:
                    description: Pull secrets for the configuration packages
                    items:
                      type: string
                    type: array
                type: object
              defaultLabel:
                properties:
                  name:
                    description: The default label name for a claim to select composition
                    type: string
                  value:
                    description: The default label value for a claim to select composition
                    type: string
                type: object
              replicas:
                description: The number of replicas to run for the Crossplane pods
                type: integer
              resourcesCrossplane:
                properties:
                  limits:
                    properties:
                      cpu:
                        description: CPU resource limits for Crossplane
                        type: string
                      memory:
                        description: Memory resource limits for Crossplane
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        description: CPU resource requests for Crossplane
                        type: string
                      memory:
                        description: Memory resource requests for Crossplane
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: Status defines the observed state of Crossplane
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    lastUpdateTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              deployedRelease:
                properties:
                  manifest:
                    type: string
                  name:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}